cart/urls.py
from django.urls import path

from cart.views import AddToCartView, CartLineDeleteView, CartLineDecreaseView, EmptyCartView

app_name = 'cart'

urlpatterns = [
    path('add/', AddToCartView.as_view(), name='add-to-cart'),
    path('cartline/delete/<int:pk>/', CartLineDeleteView.as_view(), name='cart-line-delete'),
    path('cartline/decrease/<int:pk>/', CartLineDecreaseView.as_view(), name='cart-line-decrease'),
    path('cart-empty/', EmptyCartView.as_view(), name='empty-cart'),

]

order/urls.py
from django.urls import path

from order.views import OrderServiceListView, OrderServiceDetailView, OrderServiceUpdateView, OrderServiceListFilterView
from order.views import CustomerOrdersListView, CustomerOrderDetailView

app_name = 'order'

urlpatterns = [
    path('service/list/<int:service_pk>/', OrderServiceListFilterView.as_view(), name='service-order-list'),
    path('service/today/<int:service_pk>/', OrderServiceListView.as_view(), name='service-order-today'),
    path('service/detail/<int:pk>/', OrderServiceDetailView.as_view(), name='service-order-detail'),
    path('service/update/<int:pk>/', OrderServiceUpdateView.as_view(), name='service-order-update'),
  
    path('customer/list/', CustomerOrdersListView.as_view(), name='customer-list'),
    path('customer/<int:pk>/detail/', CustomerOrderDetailView.as_view(), name='customer-detail'),
]

service/urls.py
from django.urls import path

from .views import ServiceProviderServiceCreateView, ServiceProviderServiceUpdateView, ServiceProviderServiceDeleteView, \
    ServiceProviderServiceDetailView, ServiceProviderServiceListView, ServiceProviderServiceCategoryCreateView, \
    ServiceProviderServiceCategoryUpdateView, ServiceProviderServiceCategoryDeleteView, \
    ServiceProviderDeliveryAreaCreate, ServiceProviderDeliveryUpdateView, \
    ServiceProviderDeliveryDeleteView, ServiceProviderServiceAvailableTimeCreateView, \
    ServiceProviderServiceAvailableTimeUpdateView, ServiceProviderServiceAvailableTimeDeleteView, ServiceListView

app_name = 'service'

urlpatterns = (
    path('serviceprovider/create/', ServiceProviderServiceCreateView.as_view(),
         name='service-provider-service-create'),
    path('serviceprovider/update/<int:pk>', ServiceProviderServiceUpdateView.as_view(),
         name='service-provider-service-update'),
    path('serviceprovider/delete/<int:pk>', ServiceProviderServiceDeleteView.as_view(),
         name='service-provider-service-delete'),
    path('serviceprovider/detail/<int:pk>', ServiceProviderServiceDetailView.as_view(),
         name='service-provider-service-detail'),
    path('serviceprovider/list/', ServiceProviderServiceListView.as_view(), name='service-provider-service-list'),

    path('serviceprovider/category/create/<int:service_pk>/', ServiceProviderServiceCategoryCreateView.as_view(),
         name='service-provider-service-category-create'),
    path('serviceprovider/category/update/<int:pk>/', ServiceProviderServiceCategoryUpdateView.as_view(),
         name='service-provider-service-category-update'),
    path('serviceprovider/category/delete/<int:pk>/', ServiceProviderServiceCategoryDeleteView.as_view(),
         name='service-provider-service-category-delete'),

    path('serviceprovider/deliveryarea/create/<int:service_pk>', ServiceProviderDeliveryAreaCreate.as_view(),
         name='service-provider-delivery-area-create'),
    path('serviceprovider/deliveryarea/update/<int:pk>', ServiceProviderDeliveryUpdateView.as_view(),
         name='service-provider-delivery-area-update'),
    path('serviceprovider/deliveryarea/delete/<int:pk>', ServiceProviderDeliveryDeleteView.as_view(),
         name='service-provider-delivery-area-delete'),

    path(
        'serviceprovider/availabletime/create/<int:service_pk>',
        ServiceProviderServiceAvailableTimeCreateView.as_view(),
        name='service-provider-available-time-create'
    ),
    path('serviceprovider/availabletime/update/<int:pk>', ServiceProviderServiceAvailableTimeUpdateView.as_view(),
         name='service-provider-available-time-update'),
    path('serviceprovider/availabletime/delete/<int:pk>', ServiceProviderServiceAvailableTimeDeleteView.as_view(),
         name='service-provider-available-time-delete'),

    path('list/', ServiceListView.as_view(), name='service-list')
)

yummy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin-panel'),
    path('home/', TemplateView.as_view(template_name='base.html'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('service/', include('service.urls', namespace='service')),
    path('address/', include('address.urls', namespace='address')),
    path('item/', include('item.urls', namespace='item')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models

from accounts.models import Customer
from library.models import BaseModel
from django.utils.translation import ugettext_lazy as _

from payment.models import Invoice


class Order(BaseModel):
    PREPARING_FOOD = 0
    SENDING = 1
    DELIVERED = 2
    STATUS = (
        (PREPARING_FOOD, _('preparing food')),
        (SENDING, _('sending')),
        (DELIVERED, _('delivered'))
    )
    invoice = models.OneToOneField(Invoice, verbose_name=_('invoice'), related_name='order', on_delete=models.PROTECT)
    customer = models.ForeignKey(Customer, verbose_name=_('customer'), related_name='orders', on_delete=models.PROTECT)
    status = models.PositiveSmallIntegerField(verbose_name=_('status'), choices=STATUS, default=PREPARING_FOOD)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')
        db_table = 'order'

    def __str__(self):
        return f"{self.customer} - {self.status}"

    @classmethod
    def create(cls, invoice):
        cls.objects.create(invoice=invoice, customer=invoice.customer)

service/models.py
from django.db import models
from django.utils.text import slugify

from accounts.models import ServiceProvider
from library.models import BaseModel
from django.utils.translation import ugettext_lazy as _
from address.models import ServiceAddress, Area
import uuid


class Service(BaseModel):
    RESTAURANT = 0
    CAFE = 1
    CONFECTIONERY = 2
    SUPERMARKET = 3

    SERVICE_TYPES = (
        (RESTAURANT, _('restaurant')),
        (CAFE, _('cafe')),
        (CONFECTIONERY, _('confectionery')),
        (SUPERMARKET, _('supermarket')),
    )

    uuid = models.UUIDField(default=uuid.uuid4, verbose_name=_('uuid'), unique=True, db_index=True)
    service_provider = models.ForeignKey(
        ServiceProvider,
        verbose_name=_('service provider'),
        related_name='services',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=40, verbose_name=_('name'))
    service_type = models.PositiveSmallIntegerField(verbose_name=_('service type'), choices=SERVICE_TYPES)
    minimum_purchase = models.DecimalField(max_digits=9, decimal_places=0, verbose_name=_('minimum purchase'))
    available = models.BooleanField(default=False, verbose_name=_('available'))
    logo = models.ImageField(verbose_name=_('logo'), upload_to='service/logos/', null=True, blank=True)
    banner = models.ImageField(verbose_name=_('banner'), upload_to='service/banners/', null=True, blank=True)

    address = models.OneToOneField(
        ServiceAddress,
        verbose_name=_('address'),
        related_name='services',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return f'{self.name} - {self.get_service_type_display()}'

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')
        db_table = 'service'
        ordering = ('created_time',)


class ServiceCategory(BaseModel):
    name = models.CharField(max_length=30, verbose_name=_('name'))
    slug = models.SlugField(max_length=35, verbose_name=_('slug'), allow_unicode=True)
    service = models.ForeignKey(Service, verbose_name=_('service'), related_name='categories', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.service.name}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('ServiceCategory')
        verbose_name_plural = _('ServiceCategories')
        db_table = 'service_category'


class DeliveryArea(BaseModel):
    service = models.ForeignKey(
        Service, verbose_name=_('service'), related_name='delivery_areas', on_delete=models.CASCADE
    )
    area = models.ForeignKey(Area, verbose_name=_('area'), related_name='delivery_areas', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.service.name} - {self.area}'

    class Meta:
        verbose_name = _('DeliveryArea')
        verbose_name_plural = _('DeliveryAreas')
        db_table = 'delivery_area'


class ServiceAvailableTime(BaseModel):
    SAT_DAY = 0
    SUN_DAY = 1
    MON_DAY = 2
    TUE_DAY = 3
    WED_DAY = 4
    THU_DAY = 5
    FRI_DAY = 6

    DAYS = (
        (SAT_DAY, _('saturday')),
        (SUN_DAY, _('sunday')),
        (MON_DAY, _('monday')),
        (TUE_DAY, _('tuesday')),
        (WED_DAY, _('wednesday')),
        (THU_DAY, _('thursday')),
        (FRI_DAY, _('friday'))
    )
    service = models.ForeignKey(
        Service, verbose_name=_('service'), related_name='available_times', on_delete=models.CASCADE
    )
    day = models.PositiveSmallIntegerField(verbose_name=_('day'), choices=DAYS, null=True)
    open_time = models.TimeField(verbose_name=_('open time'), null=True)
    close_time = models.TimeField(verbose_name=_('close time'), null=True)
    is_close = models.BooleanField(verbose_name=_('close day'), blank=True, null=True)

    def __str__(self):
        return f'{self.service.name} - {self.get_day_display()} - ' \
               f'{self.is_close if self.close_time else self.open_time and "-" and self.close_time}'

    class Meta:
        verbose_name = _('ServiceAvailableTime')
        verbose_name_plural = _('ServiceAvailableTimes')
        db_table = 'service_available_time'
        ordering = ('day',)

service/forms.py
from django import forms

from service.models import Service, ServiceCategory, DeliveryArea, ServiceAvailableTime


class ServiceCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'service_type', 'minimum_purchase', 'available', 'logo', 'banner')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'service_type': forms.Select(attrs={'class': 'form-control'}),
            'minimum_purchase': forms.NumberInput(attrs={'class': 'form-control'}),
            'logo': forms.FileInput(attrs={'class': 'form-control'}),
            'banner': forms.FileInput(attrs={'class': 'form-control'}),
            'available': forms.NullBooleanSelect(attrs={'class': 'form-control'}),
        }


class ServiceCategoryCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = ServiceCategory
        fields = ('name',)
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'})}


class DeliveryAreaCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = DeliveryArea
        fields = ('area',)
        widgets = {'area': forms.Select(attrs={'class': 'form-control'})}


class ServiceAvailableTimeCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = ServiceAvailableTime
        fields = ('day', 'open_time', 'close_time', 'is_close')
        widgets = {
            'day': forms.Select(attrs={'class': 'form-control'}),
            'open_time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'close_time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'is_close': forms.NullBooleanSelect(attrs={'class': 'form-control'})
        }

order/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, DetailView, UpdateView

from django_filters.views import FilterView

from order.filters import OrderFilter
from order.models import Order
from service.models import Service

from library.utils import CustomUserPasses

from accounts.models import Customer, ServiceProvider
from accounts.utils import IsCustomer


class BaseOrderServiceList(CustomUserPasses):
    model = Order

    def test_func(self):
        if not isinstance(self.request.user, ServiceProvider):
            return False
        if self.service.service_provider != self.request.user:
            return False
        return True


class BaseOrderDetailUpdate(CustomUserPasses):
    model = Order

    def test_func(self):
        order = self.get_object()
        if not isinstance(self.reqeust.user, ServiceProvider):
            return False
        if order.invoice.cart.service.service_provider != self.request.user:
            return False
        return True


@method_decorator(require_http_methods(['GET']), name='dispatch')
@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class OrderServiceListFilterView(FilterView):
    context_object_name = 'orders'
    filterset_class = OrderFilter
    template_name = 'order/service/order_filter_list.html'

    def dispatch(self, request, *args, **kwargs):
        self.service = get_object_or_404(Service, pk=self.kwargs.get('service_pk', None))
        if self.service.service_provider != self.request.user:
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Order.objects.filter(invoice__cart__service=self.service)


@method_decorator(require_http_methods(['GET']), name='dispatch')
@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class OrderServiceListView(BaseOrderServiceList, ListView):
    context_object_name = 'orders'
    template_name = 'order/service/order_list.html'

    def dispatch(self, request, *args, **kwargs):
        self.service = get_object_or_404(Service, pk=self.kwargs.get('service_pk', None))
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        today = timezone.now()
        time_filter = dict(
            created_time__day=today.strftime('%d'),
            created_time__month=today.strftime('%m'),
            created_time__year=today.strftime('%Y')
        )
        return Order.objects.exclude(is_delivered=True).filter(invoice__cart__service=self.service, **time_filter)


@method_decorator(require_http_methods(['GET']), name='dispatch')
@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class OrderServiceDetailView(BaseOrderDetailUpdate, DetailView):
    context_object_name = 'order'
    template_name = 'order/service/order_detail.html'


@method_decorator(require_http_methods(['GET', 'POST']), name='dispatch')
@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class OrderServiceUpdateView(BaseOrderDetailUpdate, UpdateView):
    fields = ('status',)
    context_object_name = 'order'
    template_name = 'order/service/order_update.html'

    def get_success_url(self):
        order = self.get_object()
        return reverse_lazy('order:service-order-list', kwargs={'service_pk': order.invoice.cart.service.id})


@method_decorator(require_http_methods(['GET']), name='dispatch')
@method_decorator(login_required(login_url=reverse_lazy('accounts:customer-login-register')), name='dispatch')
class CustomerOrdersListView(IsCustomer, ListView):
    template_name = 'order/customer/order_list.html'
    context_object_name = 'active_orders'

    def get_queryset(self):
        return Order.objects.select_related('invoice__cart').filter(customer=self.request.user, status__in=(0, 1))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['delivered_orders'] = Order.objects.select_related('invoice__cart').filter(customer=self.request.user,
                                                                                           status=2)
        return context


@method_decorator(require_http_methods(['GET']), name='dispatch')
@method_decorator(login_required(login_url=reverse_lazy('accounts:customer-login-register')), name='dispatch')
class CustomerOrderDetailView(CustomUserPasses, DetailView):
    model = Order
    template_name = 'order/customer/order_detail.html'
    context_object_name = 'order'

    def test_func(self):
        user = self.request.user
        if not isinstance(user, Customer):
            return False
        if self.get_object().customer != self.request.user:
            return False
        return True

order/templates/order/service/order_detail.html
{% extends 'base.html' %}
{% block title %}Order Detail{% endblock %}
{% block content %}

    <div style="width: 100%; padding: 40px; background-color: white">
        <div style="margin-bottom: 30px">
            <div style="padding: 20px">
                <div style="font-size: 22px">
                    <p><b>id : {{ order.id }}</b></p>
                    <p><b>status : {{ order.get_status_display }}</b></p>
                    <p><b>date time : {{ order.created_time }}</b></p>
                    <p><b>total price : {{ order.invoice.price }}$</b></p>
                </div>
            </div>

        </div>
        <h4>Lines:</h4>
        <div style="border: 1px solid #ebebeb">
            <div style="padding: 20px; text-align: center; margin-bottom: 20px">
                <div style="float: left">
                    <p style="font-size: 20px"><b>
                        Item
                    </b></p>
                </div>
                <div style="float: right">
                    <p style="font-size: 20px"><b>
                        Quantity
                    </b></p>
                </div>
            </div>
            {% for cartline in order.invoice.cart.lines.all %}
                <div style="height: 70px">
                    <div style="padding: 20px; text-align: center">
                        <div style="float: left">
                            <p style="font-size: 18px">
                                {{ cartline.item }}
                            </p>
                        </div>
                        <div style="float: right; margin-right: 30px">
                            <p style="font-size: 18px">
                                {{ cartline.quantity }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div style="margin-top: 40px">
            <a href="{% url 'order:service-order-update' order.pk %}" style="background-color: deeppink; color: white"
               class="btn">Change
                Status</a>
            </form>
        </div>
    </div>
{% endblock %}

order/templates/order/service/order_filter_list.html
{% extends 'base.html' %}
{% block title %}Payment Verification{% endblock %}
{% block content %}

    <div style="width: 100%; padding: 40px; background-color: white">
        <div style="margin-bottom: 30px">
            <form method="get">
                {{ filter.form.as_p }}
                <button type="submit" class="btn btn-warning">Filter</button>
            </form>
        </div>
        <div>
            {% for order in orders %}
                <div style="height: 200px;border: 1px solid #e2e2e2">
                    <div style="padding: 20px;">
                        <div style="float: left">
                            <div style="font-size: 18px">
                                <p>id : {{ order.id }}</p>
                                <p>status : {{ order.get_status_display }}</p>
                                <p>date time : {{ order.created_time }}</p>
                                <p> total price : {{ order.invoice.price }}$</p>
                            </div>
                        </div>
                        <div align="right" style="float: right; margin-top: 60px">
                            <a href="{% url 'order:service-order-detail' order.pk %}"
                               class="btn" style="background-color: deeppink; color: white">Show Factor</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

order/templates/order/service/order_list.html
{% extends 'base.html' %}
{% block title %}Payment Verification{% endblock %}
{% block content %}
    <h6>Today: {% now "Y-m-d" %}</h6>
    <div style="width: 100%; padding: 40px; background-color: white">
        {% for order in orders %}
            <div style="height: 200px;border: 1px solid #e2e2e2">
                <div style="padding: 20px;">
                    <div style="float: left">
                        <div style="font-size: 18px">
                            <p>id : {{ order.id }}</p>
                            <p>status : {{ order.get_status_display }}</p>
                            <p>date time : {{ order.created_time }}</p>
                            <p> total price : {{ order.invoice.price }}$</p>
                        </div>
                    </div>
                    <div align="right" style="float: right; margin-top: 60px">
                        <a href="{% url 'order:service-order-detail' order.pk %}"
                           class="btn" style="background-color: deeppink; color: white">Show Factor</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

order/templates/order/service/order_update.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" value="submit" class="btn btn-primary">Update</button>
    </form>
    <a href="{% url 'order:service-order-detail' object.pk %}" class="btn btn-warning" style="margin-top: 20px">cancel</a>
{% endblock %}