address/urls.py
from django.urls import path

from .views import CustomerAddressCreateView, CustomerAddressUpdateView, CustomerAddressDeleteView, \
    ServiceAddressCreateView, ServiceAddressUpdateView, CustomerAddressListView

app_name = 'address'

urlpatterns = [
    path('customer/create/', CustomerAddressCreateView.as_view(), name='customer-address-create'),
    path('service/create/<int:service_pk>/', ServiceAddressCreateView.as_view(), name='service-address-create'),

    path('customer/update/<int:pk>/', CustomerAddressUpdateView.as_view(), name='customer-address-update'),
    path('service/update/<int:pk>/', ServiceAddressUpdateView.as_view(), name='service-address-update'),

    path('customer/delete/<int:pk>/', CustomerAddressDeleteView.as_view(), name='customer-address-delete'),
    path('customer/list/', CustomerAddressListView.as_view(), name='customer-address-list'),
]

cart/urls.py
from django.urls import path

from cart.views import AddToCartView, CartLineDeleteView, CartLineDecreaseView, EmptyCartView

app_name = 'cart'

urlpatterns = [
    path('add/', AddToCartView.as_view(), name='add-to-cart'),
    path('cartline/delete/<int:pk>/', CartLineDeleteView.as_view(), name='cart-line-delete'),
    path('cartline/decrease/<int:pk>/', CartLineDecreaseView.as_view(), name='cart-line-decrease'),
    path('cart-empty/', EmptyCartView.as_view(), name='empty-cart'),

]

item/urls.py
from django.urls import path
from item.views import ItemUpdateView, ItemDetailView, ItemDeleteView, ServiceProviderItemDetailView, ItemCreateView, \
    ItemListView, ServiceCategoryItemListView

app_name = 'item'

urlpatterns = [
    path('create/<int:service_pk>/<int:category_pk>/', ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('detail-serviceprovider/<int:pk>/', ServiceProviderItemDetailView.as_view(), name='detail-service-provider'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('<int:service_pk>/list/', ItemListView.as_view(), name='list'),
    path(
        'serviceprovider/<int:service_pk>/<int:category_pk>/list/', ServiceCategoryItemListView.as_view(),
        name='service-provider-list'),
]

order/urls.py
from django.urls import path

from order.views import OrderServiceListView, OrderServiceDetailView, OrderServiceUpdateView, OrderServiceListFilterView
from order.views import CustomerOrdersListView, CustomerOrderDetailView

app_name = 'order'

urlpatterns = [
    path('service/list/<int:service_pk>/', OrderServiceListFilterView.as_view(), name='service-order-list'),
    path('service/today/<int:service_pk>/', OrderServiceListView.as_view(), name='service-order-today'),
    path('service/detail/<int:pk>/', OrderServiceDetailView.as_view(), name='service-order-detail'),
    path('service/update/<int:pk>/', OrderServiceUpdateView.as_view(), name='service-order-update'),
  
    path('customer/list/', CustomerOrdersListView.as_view(), name='customer-list'),
    path('customer/<int:pk>/detail/', CustomerOrderDetailView.as_view(), name='customer-detail'),
]

service/urls.py
from django.urls import path

from .views import ServiceProviderServiceCreateView, ServiceProviderServiceUpdateView, ServiceProviderServiceDeleteView, \
    ServiceProviderServiceDetailView, ServiceProviderServiceListView, ServiceProviderServiceCategoryCreateView, \
    ServiceProviderServiceCategoryUpdateView, ServiceProviderServiceCategoryDeleteView, \
    ServiceProviderDeliveryAreaCreate, ServiceProviderDeliveryUpdateView, \
    ServiceProviderDeliveryDeleteView, ServiceProviderServiceAvailableTimeCreateView, \
    ServiceProviderServiceAvailableTimeUpdateView, ServiceProviderServiceAvailableTimeDeleteView, ServiceListView

app_name = 'service'

urlpatterns = (
    path('serviceprovider/create/', ServiceProviderServiceCreateView.as_view(),
         name='service-provider-service-create'),
    path('serviceprovider/update/<int:pk>', ServiceProviderServiceUpdateView.as_view(),
         name='service-provider-service-update'),
    path('serviceprovider/delete/<int:pk>', ServiceProviderServiceDeleteView.as_view(),
         name='service-provider-service-delete'),
    path('serviceprovider/detail/<int:pk>', ServiceProviderServiceDetailView.as_view(),
         name='service-provider-service-detail'),
    path('serviceprovider/list/', ServiceProviderServiceListView.as_view(), name='service-provider-service-list'),

    path('serviceprovider/category/create/<int:service_pk>/', ServiceProviderServiceCategoryCreateView.as_view(),
         name='service-provider-service-category-create'),
    path('serviceprovider/category/update/<int:pk>/', ServiceProviderServiceCategoryUpdateView.as_view(),
         name='service-provider-service-category-update'),
    path('serviceprovider/category/delete/<int:pk>/', ServiceProviderServiceCategoryDeleteView.as_view(),
         name='service-provider-service-category-delete'),

    path('serviceprovider/deliveryarea/create/<int:service_pk>', ServiceProviderDeliveryAreaCreate.as_view(),
         name='service-provider-delivery-area-create'),
    path('serviceprovider/deliveryarea/update/<int:pk>', ServiceProviderDeliveryUpdateView.as_view(),
         name='service-provider-delivery-area-update'),
    path('serviceprovider/deliveryarea/delete/<int:pk>', ServiceProviderDeliveryDeleteView.as_view(),
         name='service-provider-delivery-area-delete'),

    path(
        'serviceprovider/availabletime/create/<int:service_pk>',
        ServiceProviderServiceAvailableTimeCreateView.as_view(),
        name='service-provider-available-time-create'
    ),
    path('serviceprovider/availabletime/update/<int:pk>', ServiceProviderServiceAvailableTimeUpdateView.as_view(),
         name='service-provider-available-time-update'),
    path('serviceprovider/availabletime/delete/<int:pk>', ServiceProviderServiceAvailableTimeDeleteView.as_view(),
         name='service-provider-available-time-delete'),

    path('list/', ServiceListView.as_view(), name='service-list')
)

yummy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin-panel'),
    path('home/', TemplateView.as_view(template_name='base.html'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('service/', include('service.urls', namespace='service')),
    path('address/', include('address.urls', namespace='address')),
    path('item/', include('item.urls', namespace='item')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/forms.py
from django import forms

from service.models import Service, ServiceCategory, DeliveryArea, ServiceAvailableTime


class ServiceCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'service_type', 'minimum_purchase', 'available', 'logo', 'banner')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'service_type': forms.Select(attrs={'class': 'form-control'}),
            'minimum_purchase': forms.NumberInput(attrs={'class': 'form-control'}),
            'logo': forms.FileInput(attrs={'class': 'form-control'}),
            'banner': forms.FileInput(attrs={'class': 'form-control'}),
            'available': forms.NullBooleanSelect(attrs={'class': 'form-control'}),
        }


class ServiceCategoryCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = ServiceCategory
        fields = ('name',)
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'})}


class DeliveryAreaCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = DeliveryArea
        fields = ('area',)
        widgets = {'area': forms.Select(attrs={'class': 'form-control'})}


class ServiceAvailableTimeCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = ServiceAvailableTime
        fields = ('day', 'open_time', 'close_time', 'is_close')
        widgets = {
            'day': forms.Select(attrs={'class': 'form-control'}),
            'open_time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'close_time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
            'is_close': forms.NullBooleanSelect(attrs={'class': 'form-control'})
        }

service/views.py
from abc import ABC

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.shortcuts import get_object_or_404, redirect

from django_filters.views import FilterView

from accounts.utils import IsServiceProvider
from service.forms import ServiceCreateUpdateForm, ServiceCategoryCreateUpdateForm, DeliveryAreaCreateUpdateForm, \
    ServiceAvailableTimeCreateUpdateForm
from service.filters import ServiceFilter
from service.models import Service, ServiceCategory, DeliveryArea, ServiceAvailableTime
from service.utils import CustomServiceIsServiceProvider


class BaseServiceView(ABC):
    model = Service
    form_class = ServiceCreateUpdateForm
    template_name = 'service/service_provider/create_update_form.html'


class BaseCreateView(ABC, IsServiceProvider):
    def test_func(self):
        return self.service.service_provider == self.request.user and super().test_func()

    def get_success_url(self):
        return reverse_lazy('service:service-provider-service-detail', kwargs={'pk': self.service.pk})

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.service = get_object_or_404(Service, pk=self.kwargs['service_pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service'] = self.service
        return context


class BaseOtherView(IsServiceProvider):
    def get_success_url(self):
        return reverse_lazy('service:service-provider-service-detail', kwargs={'pk': self.object.service.pk})

    def test_func(self):
        obj = self.get_object()
        return obj.service.service_provider == self.request.user and super().test_func()


class BaseServiceCategory(ABC, BaseOtherView):
    model = ServiceCategory
    form_class = ServiceCategoryCreateUpdateForm
    template_name = 'service_category/create_update_form.html'


class BaseDeliveryArea(ABC, BaseOtherView):
    model = DeliveryArea
    form_class = DeliveryAreaCreateUpdateForm
    template_name = 'delivery_area/create_update_form.html'


class BaseServiceAvailableTime(ABC, BaseOtherView):
    model = ServiceAvailableTime
    form_class = ServiceAvailableTimeCreateUpdateForm
    template_name = 'service_available_time/create_update_form.html'


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceCreateView(BaseServiceView, IsServiceProvider, CreateView):
    success_url = reverse_lazy('service:service-provider-service-list')

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.service_provider = self.request.user
        instance.save()
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceUpdateView(BaseServiceView, CustomServiceIsServiceProvider, UpdateView):
    success_url = reverse_lazy('service:service-provider-service-list')


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceDeleteView(BaseServiceView, CustomServiceIsServiceProvider, DeleteView):
    template_name = 'service/service_provider/delete_form.html'
    success_url = reverse_lazy('service:service-provider-service-list')


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceDetailView(BaseServiceView, CustomServiceIsServiceProvider, DetailView):
    context_object_name = 'service'
    template_name = 'service/service_provider/detail.html'


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceListView(BaseServiceView, IsServiceProvider, ListView):
    context_object_name = 'services'
    template_name = 'service/service_provider/list.html'

    def get_queryset(self):
        return super().get_queryset().filter(service_provider=self.request.user)


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceCategoryCreateView(BaseCreateView, CreateView):
    model = ServiceCategory
    form_class = ServiceCategoryCreateUpdateForm
    template_name = 'service_category/create_update_form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.service = self.service
        instance.save()
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceCategoryUpdateView(BaseServiceCategory, UpdateView):
    pass


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceCategoryDeleteView(BaseServiceCategory, DeleteView):
    context_object_name = 'category'
    template_name = 'service_category/delete_form.html'


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderDeliveryAreaCreate(BaseCreateView, CreateView):
    model = DeliveryArea
    form_class = DeliveryAreaCreateUpdateForm
    template_name = 'delivery_area/create_update_form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.service = self.service
        instance.save()
        return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderDeliveryUpdateView(BaseDeliveryArea, UpdateView):
    pass


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderDeliveryDeleteView(BaseDeliveryArea, DeleteView):
    context_object_name = 'delivery'
    template_name = 'delivery_area/delete_form.html'


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceAvailableTimeCreateView(BaseCreateView, CreateView):
    model = ServiceAvailableTime
    form_class = ServiceAvailableTimeCreateUpdateForm
    template_name = 'service_available_time/create_update_form.html'

    def form_valid(self, form):
        with transaction.atomic():
            instance = form.save(commit=False)
            if self.service.available_times.filter(day=instance.day).exists():
                messages.info(self.request, f'This Service {self.service.name} has this day time', 'danger')
                return redirect(self.get_success_url())
            instance.service = self.service
            instance.save()
            return super().form_valid(form)


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceAvailableTimeUpdateView(BaseServiceAvailableTime, UpdateView):
    pass


@method_decorator(login_required(login_url=reverse_lazy('accounts:service-provider-login')), name='dispatch')
class ServiceProviderServiceAvailableTimeDeleteView(BaseServiceAvailableTime, DeleteView):
    context_object_name = 'available_time'
    template_name = 'service_available_time/delete_form.html'


class ServiceListView(FilterView):
    model = Service
    context_object_name = 'services'
    template_name = 'service/list.html'
    filterset_class = ServiceFilter
    queryset = Service.objects.filter(available=True)

service/templates/service/service_provider/create_update_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" class="btn btn-warning">
    </form>
    <a href="{% url 'service:service-provider-service-list' %}" class="btn btn-warning" style="margin-top: 20px">cancel</a>
{% endblock %}

service/templates/service/service_provider/delete_form.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure to delete service ({{ service.name }})?</p>
            <input type="submit" value="delete" class="btn btn-danger">
        </form>
        <a href="{% url 'service:service-provider-service-list' %}" class="btn btn-warning" style="margin-top: 20px">cancel</a>
    </div>
{% endblock %}

service/templates/service/service_provider/detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <h4 class="text-warning">Service Detail</h4>
        <p>Service name : {{ service.name }}</p>
        <p>Service minimum purchase : {{ service.minimum_purchase }}</p>
        <p>Service minimum purchase : {{ service.get_service_type_display }}</p>
        {% if service.available %}
            <p>Service available : Yes</p>
        {% else %}
            <p>Service available : No</p>
        {% endif %}
        {% if service.logo %}
            <p>Service Logo Image : <img src="{{ service.logo.url }}"></p>
        {% else %}
            <p>Service Logo Image : Not Yet Uploaded</p>
        {% endif %}
        {% if service.banner %}
            <p>Service Banner Image : <img src="{{ service.banner.url }}"></p>
        {% else %}
            <p>Service Logo Image : Not Yet Uploaded</p>
        {% endif %}

        <br>
        <hr>
        <div style="margin-top: 20px; margin-bottom: 20px">
            <h4 class="text-warning">Service Address</h4>
            {% if service.address %}
                <p>state : {{ service.address.state.name }}</p>
                <p>city : {{ service.address.city.name }}</p>
                <p>area : {{ service.address.area.name }}</p>
                <p>street : {{ service.address.street }}</p>
                <p>alley : {{ service.address.alley }}</p>
                <p>floor : {{ service.address.floor }}</p>
                <p>plaque : {{ service.address.plaque }}</p>
                <a href="{% url 'address:service-address-update' service.address.pk %}">Update Address</a>
            {% else %}
                <p>Your service yet not has address!<a
                        href="{% url 'address:service-address-create' service.pk %}">Create Address</a></p>
            {% endif %}
        </div>
        <hr>
        <div class="service-category" style="margin-top: 20px; margin-bottom: 20px">
            <h4 class="text-warning">Service Categories</h4>
            <br><br>
            <a href="{% url 'service:service-provider-service-category-create' service.pk %}">Create new category</a>
            <br><br>
            <ul class="list-group">
                {% for category in service.categories.all %}
                    <li class="list-group-item">
                        {{ category.name }}
                        <div align="right">
                            <a href="{% url 'service:service-provider-service-category-update' category.pk %}"
                               class="btn btn-warning"
                               style="margin-right: 10px">Update</a>
                            <a href="{% url 'item:service-provider-list' service.pk category.pk %}"
                               class="btn btn-primary"
                               style="margin-right: 10px">Detail</a>
                            <a href="{% url 'service:service-provider-service-category-delete' category.pk %}"
                               class="btn btn-danger">Delete</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <hr>
        <div class="delivery-area" style="margin-top: 20px; margin-bottom: 20px">
            <h4 class="text-warning">Service Delivery Area</h4>
            <br>
            <br>
            <a href="{% url 'service:service-provider-delivery-area-create' service.pk %}"> Create new delivery area</a>
            <br>
            <br>
            {% with deliveries=service.delivery_areas.all %}
                {% if deliveries %}
                    {% for delivery in deliveries %}
                        <li class="list-group-item">
                            {{ delivery.area.name }}
                            <div align="right">
                                <a href="{% url 'service:service-provider-delivery-area-update' delivery.pk %}"
                                   class="btn btn-warning" style="margin-right: 10px">Update</a>
                                <a href="{% url 'service:service-provider-delivery-area-delete' delivery.pk %}"
                                   class="btn btn-danger">Delete</a>
                            </div>
                        </li>
                    {% endfor %}

                {% endif %}
            {% endwith %}
        </div>
        <hr>
        <div class="available-time" style="margin-top: 20px; margin-bottom: 20px">
            <h4 class="text-warning">Service Available Time</h4>
            <br>
            <br>
            <a href="{% url 'service:service-provider-available-time-create' service.pk %}"> Create new available
                time</a>
            <br>
            <br>
            {% with availabletimes=service.available_times.all %}
                {% if availabletimes %}
                    {% for availabletime in availabletimes %}
                        <li class="list-group-item">
                            {{ availabletime.get_day_display }} | open at : {{ availabletime.open_time }} | close at
                            : {{ availabletime.close_time }} | is close : {{ availabletime.is_close }}
                            <div align="right">
                                <a href="{% url 'service:service-provider-available-time-update' availabletime.pk %}"
                                   class="btn btn-warning" style="margin-right: 10px">Update</a>
                                <a href="{% url 'service:service-provider-available-time-delete' availabletime.pk %}"
                                   class="btn btn-danger">Delete</a>
                            </div>
                        </li>
                    {% endfor %}

                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endblock %}

service/templates/service/service_provider/list.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'service:service-provider-service-create' %}">Create new service</a>
    <br><br>
    <ul class="list-group">
        {% for service in services %}
            <li class="list-group-item">
                <div style="float: left">{{ service.name }}</div>
                <div align="right" style="float: right">
                    <a href="{% url 'service:service-provider-service-update' service.pk %}"
                       class="btn btn-warning" style="margin-right: 10px">Update</a>
                    <a href="{% url 'service:service-provider-service-detail' service.pk %}"
                       class="btn btn-primary" style="margin-right: 10px">Detail</a>
                    <a href="{% url 'service:service-provider-service-delete' service.pk %}"
                       class="btn btn-danger" style="margin-right: 10px">Delete</a>
                    <a href="{% url 'order:service-order-today' service.pk %}"
                       class="btn" style="color: white; background-color: #ff92ec; margin-right: 10px">Today Orders</a>
                    <a href="{% url 'order:service-order-list' service.pk %}"
                       class="btn" style="color: white; background-color: deeppink">All Orders</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}