accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('customer/profile/', views.CustomerProfileView.as_view(), name='customer-profile'),
    path('customer/profile-update/', views.CustomerProfileUpdateView.as_view(), name='customer-profile-update'),
    path('customer/login-register/', views.CustomerLoginRegisterView.as_view(), name='customer-login-register'),
    path('customer/code-confirm/', views.CustomerPhoneNumberConfirmView.as_view(), name='customer-code-confirm'),
    path('customer/password-confirm/', views.CustomerPasswordConfirmView.as_view(), name='customer-password-confirm'),
    path('customer/set-password/', views.CustomerSetPasswordView.as_view(), name='customer-set-password'),
    path('customer/change-password/', views.CustomerChangePasswordView.as_view(), name='customer-change-password'),
    path('customer/logout/', views.CustomerLogoutView.as_view(), name='customer-logout'),
    path('serviceprovider/registration/', views.ServiceProviderRegistrationView.as_view(),
         name='service-provider-registration'),
    path('serviceprovider/login/', views.ServiceProviderLoginView.as_view(), name='service-provider-login'),
    path('serviceprovider/profile/', views.ServiceProviderProfileView.as_view(), name='service-provider-profile'),
    path('serviceprovider/change-password/', views.ServiceProviderChangePasswordView.as_view(),
         name='service-provider-change-password'),
    path('serviceprovider/logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:service-provider-login')),
         name='service-provider-logout'),
]

address/urls.py
from django.urls import path

from .views import CustomerAddressCreateView, CustomerAddressUpdateView, CustomerAddressDeleteView, \
    ServiceAddressCreateView, ServiceAddressUpdateView, CustomerAddressListView

app_name = 'address'

urlpatterns = [
    path('customer/create/', CustomerAddressCreateView.as_view(), name='customer-address-create'),
    path('service/create/<int:service_pk>/', ServiceAddressCreateView.as_view(), name='service-address-create'),

    path('customer/update/<int:pk>/', CustomerAddressUpdateView.as_view(), name='customer-address-update'),
    path('service/update/<int:pk>/', ServiceAddressUpdateView.as_view(), name='service-address-update'),

    path('customer/delete/<int:pk>/', CustomerAddressDeleteView.as_view(), name='customer-address-delete'),
    path('customer/list/', CustomerAddressListView.as_view(), name='customer-address-list'),
]

cart/urls.py
from django.urls import path

from cart.views import AddToCartView, CartLineDeleteView, CartLineDecreaseView, EmptyCartView

app_name = 'cart'

urlpatterns = [
    path('add/', AddToCartView.as_view(), name='add-to-cart'),
    path('cartline/delete/<int:pk>/', CartLineDeleteView.as_view(), name='cart-line-delete'),
    path('cartline/decrease/<int:pk>/', CartLineDecreaseView.as_view(), name='cart-line-decrease'),
    path('cart-empty/', EmptyCartView.as_view(), name='empty-cart'),

]

order/urls.py
from django.urls import path

from order.views import OrderServiceListView, OrderServiceDetailView, OrderServiceUpdateView, OrderServiceListFilterView
from order.views import CustomerOrdersListView, CustomerOrderDetailView

app_name = 'order'

urlpatterns = [
    path('service/list/<int:service_pk>/', OrderServiceListFilterView.as_view(), name='service-order-list'),
    path('service/today/<int:service_pk>/', OrderServiceListView.as_view(), name='service-order-today'),
    path('service/detail/<int:pk>/', OrderServiceDetailView.as_view(), name='service-order-detail'),
    path('service/update/<int:pk>/', OrderServiceUpdateView.as_view(), name='service-order-update'),
  
    path('customer/list/', CustomerOrdersListView.as_view(), name='customer-list'),
    path('customer/<int:pk>/detail/', CustomerOrderDetailView.as_view(), name='customer-detail'),
]

service/urls.py
from django.urls import path

from .views import ServiceProviderServiceCreateView, ServiceProviderServiceUpdateView, ServiceProviderServiceDeleteView, \
    ServiceProviderServiceDetailView, ServiceProviderServiceListView, ServiceProviderServiceCategoryCreateView, \
    ServiceProviderServiceCategoryUpdateView, ServiceProviderServiceCategoryDeleteView, \
    ServiceProviderDeliveryAreaCreate, ServiceProviderDeliveryUpdateView, \
    ServiceProviderDeliveryDeleteView, ServiceProviderServiceAvailableTimeCreateView, \
    ServiceProviderServiceAvailableTimeUpdateView, ServiceProviderServiceAvailableTimeDeleteView, ServiceListView

app_name = 'service'

urlpatterns = (
    path('serviceprovider/create/', ServiceProviderServiceCreateView.as_view(),
         name='service-provider-service-create'),
    path('serviceprovider/update/<int:pk>', ServiceProviderServiceUpdateView.as_view(),
         name='service-provider-service-update'),
    path('serviceprovider/delete/<int:pk>', ServiceProviderServiceDeleteView.as_view(),
         name='service-provider-service-delete'),
    path('serviceprovider/detail/<int:pk>', ServiceProviderServiceDetailView.as_view(),
         name='service-provider-service-detail'),
    path('serviceprovider/list/', ServiceProviderServiceListView.as_view(), name='service-provider-service-list'),

    path('serviceprovider/category/create/<int:service_pk>/', ServiceProviderServiceCategoryCreateView.as_view(),
         name='service-provider-service-category-create'),
    path('serviceprovider/category/update/<int:pk>/', ServiceProviderServiceCategoryUpdateView.as_view(),
         name='service-provider-service-category-update'),
    path('serviceprovider/category/delete/<int:pk>/', ServiceProviderServiceCategoryDeleteView.as_view(),
         name='service-provider-service-category-delete'),

    path('serviceprovider/deliveryarea/create/<int:service_pk>', ServiceProviderDeliveryAreaCreate.as_view(),
         name='service-provider-delivery-area-create'),
    path('serviceprovider/deliveryarea/update/<int:pk>', ServiceProviderDeliveryUpdateView.as_view(),
         name='service-provider-delivery-area-update'),
    path('serviceprovider/deliveryarea/delete/<int:pk>', ServiceProviderDeliveryDeleteView.as_view(),
         name='service-provider-delivery-area-delete'),

    path(
        'serviceprovider/availabletime/create/<int:service_pk>',
        ServiceProviderServiceAvailableTimeCreateView.as_view(),
        name='service-provider-available-time-create'
    ),
    path('serviceprovider/availabletime/update/<int:pk>', ServiceProviderServiceAvailableTimeUpdateView.as_view(),
         name='service-provider-available-time-update'),
    path('serviceprovider/availabletime/delete/<int:pk>', ServiceProviderServiceAvailableTimeDeleteView.as_view(),
         name='service-provider-available-time-delete'),

    path('list/', ServiceListView.as_view(), name='service-list')
)

yummy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin-panel'),
    path('home/', TemplateView.as_view(template_name='base.html'), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('service/', include('service.urls', namespace='service')),
    path('address/', include('address.urls', namespace='address')),
    path('item/', include('item.urls', namespace='item')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/admin_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Yummy</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link active" aria-current="page" href="#">Home</a>#}
                {#                </li>#}
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link" href="#">Cart</a>#}
                {#                </li>#}
                {#                <li class="nav-item dropdown">#}
                {#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
                {#                       data-bs-toggle="dropdown" aria-expanded="false">#}
                {#                        Categories#}
                {#                    </a>#}
                {#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown"></ul>#}
                {#                </li>#}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin Panel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/logout">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/login">Login</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-danger" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/inc/customer_navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: white; height: 80px">
    <div class="container-fluid">
        <a class="navbar-brand" style="color: deeppink" href="{% url 'service:service-list' %}"><b>Yummy</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:customer-profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'order:customer-list' %}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'address:customer-address-list' %}">Addresses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:customer-logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:customer-login-register' %}">Sign up/Login</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn" style="color: deeppink; border: 1px solid deeppink" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

templates/inc/service_provider_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Yummy</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
{#                <li class="nav-item">#}
{#                    <a class="nav-link active" aria-current="page" href="#">Home</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Cart</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
{#                       data-bs-toggle="dropdown" aria-expanded="false">#}
{#                        Categories#}
{#                    </a>#}
{#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown"></ul>#}
{#                </li>#}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:service-provider-profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'service:service-provider-service-list' %}">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:service-provider-logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:service-provider-registration' %}">Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:service-provider-login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-danger" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>